#!/bin/bash
#
# chkconfig: 35 90 12
# description: Camerasp server
#
# Get function from functions library
. /lib/lsb/init-functions
# Start the service Camerasp
start() {
        initlog -c "echo -n Starting Camerasp server: "
        /home/pi/projects/camerasp/src/camerasp
        ### Create the lock file ###
        touch /var/lock/subsys/camerasp
        success $"Camerasp server startup"
        echo
}
# Restart the service Camerasp
stop() {
        initlog -c "echo -n Stopping Camerasp server: "
        killproc Camerasp
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/Camerasp
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status Camerasp
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0